#!/bin/bash

printf "Content-type: text/plain\n\n"
printf "[%s] [%s] [%s] [%s] [%s] [%s]\n" ${PATH_INFO----} ${CGI_LOCAL----} \
  ${CGI_GLOBAL----} ${1----} ${QUERY_STRING----} ${HTTP_TOKEN_CLAIM_USER----}
printf "example error message\n" > /dev/stderr
exit 0
