#!/bin/bash

printf "Content-type: text/plain\n\n"
printf "PATH_INFO [%s]\n" ${PATH_INFO}
printf "CGI_GLOBAL [%s]\n" ${CGI_GLOBAL}
printf "Arg 1 [%s]\n" ${1}
printf "QUERY_STRING [%s]\n" ${QUERY_STRING}
printf "HTTP_TOKEN_CLAIM_USER [%s]\n" ${HTTP_TOKEN_CLAIM_USER}
if [ -z ${CGI_LOCAL+x} ]; then 
	printf "CGI_LOCAL is unset\n" 
else
	printf "CGI_LOCAL is set to [%s]\n" ${CGI_LOCAL}
fi
printf "example error message\n" > /dev/stderr
exit 0
